name: Continuous integration workflow (Node.js)

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
    - name: npm run eslint
      run: npm run eslint
    - name: npm run test-coverage
      run: npm run test-coverage
    - name: npm run test-report
      run: npm run test-report
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.0
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
