name: Release workflow

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Create release with artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create tar artifact
        run: |
          tar -czvf ${{ github.ref_name }}.tar.gz .
      - name: Create zip artifact
        run: |
          zip -j -r ${{ github.ref_name }} . -x "*.tar.gz"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload release tar artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.ref_name }}.tar.gz
          asset_name: ${{ github.ref_name }}.tar.gz
          asset_content_type: application/zip
      - name: Upload release zip artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.ref_name }}.zip
          asset_name: ${{ github.ref_name }}.zip
          asset_content_type: application/zip
      